using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Input;
using TheSphinx.Core.Models;

namespace GUI.Views
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            LoadData();
        }

        private void LoadData()
        {
            List<Account> accounts = App.AccountLogic.Read().ToList();

            if (accounts != null)
                dataGrid.ItemsSource = accounts;
        }

        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid.Columns[0].Header = "Id";
            dataGrid.Columns[1].Header = "Source";
            dataGrid.Columns[2].Visibility = Visibility.Hidden;
        }

        private void DataGridRow_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {

        }

        private void btnCreate_Click(object sender, RoutedEventArgs e)
        {

        }

        private void btnEdit_Click(object sender, RoutedEventArgs e)
        {

        }

        private void btnDelete_Click(object sender, RoutedEventArgs e)
        {

        }

        private void btnSearch_Click(object sender, RoutedEventArgs e)
        {
            List<Account> accounts = App.AccountLogic.Read();
            List<Account> result = new List<Account>();

            string searchString = tbSearch.Text;

            if (searchString == "")
            {
                dataGrid.ItemsSource = accounts;
                return;
            }

            foreach (Account account in accounts)
            {
                if (account.Source.Contains(searchString))
                    result.Add(account);
                else
                    foreach (KeyValuePair<string, Field> field in account.Fields.Where(req => !req.Value.Encrypted))
                        if (field.Key.Contains(searchString) || field.Value.Value.Contains(searchString))
                        {
                            result.Add(account);
                            break;
                        }
            }

            dataGrid.ItemsSource = result;
        }
    }
}
