using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using TheSphinx.Core.Logic;
using TheSphinx.Core.Models;

namespace TheSphinx.GUI.Views
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            while (true)
            {
                try
                {
                    string password = App.PasswordController.GetPassword(PasswordController.PasswordType.general);
                    ContextInitializer.Initialize(password);
                    break;
                }
                catch (OperationCanceledException ex)
                {
                    Environment.Exit(0);
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message, "Incorrect password!", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }

            InitializeComponent();
            LoadData();
        }

        private void LoadData()
        {
            List<Account> accounts = App.AccountLogic.Read().ToList();

            if (accounts != null)
                dataGrid.ItemsSource = accounts;
        }

        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid.Columns[0].Header = "Id";
            dataGrid.Columns[1].Header = "Source";
            dataGrid.Columns[2].Visibility = Visibility.Hidden;
        }

        private void DataGridRow_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Account account = (sender as DataGridRow).Item as Account;
            account = App.AccountLogic.Read(account.Id, App.PasswordController.GetPassword(PasswordController.PasswordType.fields));

            AccountWindow window = new AccountWindow(account);
            window.ShowDialog();
        }

        private void btnCreate_Click(object sender, RoutedEventArgs e)
        {
            AccountWindow window = new AccountWindow(new Account());
            window.ShowDialog();
        }

        private void btnEdit_Click(object sender, RoutedEventArgs e)
        {
            if (dataGrid.SelectedItem != null)
            {
                Account account = dataGrid.SelectedItem as Account;
                account = App.AccountLogic.Read(account.Id, App.PasswordController.GetPassword(PasswordController.PasswordType.fields));

                AccountWindow window = new AccountWindow(account);
                window.ShowDialog();
            }
        }

        private void btnDelete_Click(object sender, RoutedEventArgs e)
        {
            if (dataGrid.SelectedItem != null)
            {
                Account account = dataGrid.SelectedItem as Account;
                App.AccountLogic.Delete(account.Id);
            }
        }

        private void btnSearch_Click(object sender, RoutedEventArgs e)
        {
            List<Account> accounts = App.AccountLogic.Read();
            List<Account> result = new List<Account>();

            string searchString = tbSearch.Text;

            if (searchString == "")
            {
                dataGrid.ItemsSource = accounts;
                return;
            }

            foreach (Account account in accounts)
            {
                if (account.Source.Contains(searchString))
                {
                    result.Add(account);
                }
                else
                {
                    foreach (KeyValuePair<string, Field> field in account.Fields.Where(req => !req.Value.Encrypted))
                    {
                        if (field.Key.Contains(searchString) || field.Value.Value.Contains(searchString))
                        {
                            result.Add(account);
                            break;
                        }
                    }
                }
            }

            dataGrid.ItemsSource = result;
        }
    }
}
